version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: helpdesk
      POSTGRES_USER: helpdesk
      POSTGRES_PASSWORD: helpdesk_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U helpdesk"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      # Database
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: helpdesk
      POSTGRES_USER: helpdesk
      POSTGRES_PASSWORD: helpdesk_password
      
      # Django
      DJANGO_HELPDESK_SECRET_KEY: local-dev-secret-key-change-in-production
      DEBUG: "True"
      ALLOWED_HOSTS: localhost,127.0.0.1
      
      # Admin user
      ADMIN_PASSWORD: admin123
      
      # Gunicorn
      GUNICORN_WORKERS: 2
      PORT: 8000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - media_data:/data/media
      - static_data:/data/static

volumes:
  postgres_data:
  media_data:
  static_data:
